[program:api]
directory=/myNas/server
command=/usr/bin/env bash -c "npm run --prefix /myNas/server/ dev"
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
user=root
# redirect_stderr=true
stderr_logfile=/myNas/log/supervisor.stderr.log
stdout_logfile=/myNas/log/supervisor.stdout.log
environment=NODE_ENV="production"

[program:job]
directory=/myNas/server
command=/usr/bin/env bash -c "npm run --prefix /myNas/server/ job"
autostart=true
autorestart=true
startsecs=5
stopasgroup=true
killasgroup=true
user=root
# redirect_stderr=true
stderr_logfile=/myNas/log/supervisor.stderr.log
stdout_logfile=/myNas/log/supervisor.stdout.log
environment=NODE_ENV="production"
